### ISSUE TITLE
Moodle 2.8.2 - new awarding rule button returns blank page

### ISSUE THREAD

**Issue by meggoodine** [discendum/obf-moodle#1]
From the badge list, click on badge details> awarding rules. The "create new awarding rule" button returns a blank page.

![awarding_rule](https://cloud.githubusercontent.com/assets/10815904/6006479/a207be80-aac7-11e4-9aeb-4c79f20bca64.png)

**Comment by meggoodine** [comment]
With debugging turned on: 
Warning: require_once(/var/www/moodle-2.8.2/local/obf/class/criterion/criterionbase.php): failed to open stream: No such file or directory in /var/www/moodle-2.8.2/local/obf/criterion.php on line 7

Fatal error: require_once(): Failed opening required '/var/www/moodle-2.8.2/local/obf/class/criterion/criterionbase.php' (include_path='/var/www/moodle-2.8.2/lib/zend:/var/www/moodle-2.8.2/lib/pear:.:/usr/share/pear:/usr/share/php') in /var/www/moodle-2.8.2/local/obf/criterion.php on line 7

**Comment by meggoodine** [comment]
Sorry, I closed this

**Comment by oinp** [comment]
Thanks for the report. The criterion page tried to include a file that was removed a while ago. The file still existed in our test system and that is why we didn't see the error. This should be fixed now.

**Comment by meggoodine** [comment]
Does something need to be refreshed at our end? I'm still getting the same error.

Thanks

**Comment by oinp** [comment]
Oh yes, sorry. Download the latest version here from GitHub and copy the files to plugin directory.
