### ISSUE TITLE
OBF causes course deletion to break

### ISSUE THREAD

**Issue by kkiiskin** [discendum/obf-moodle#10]
When deleting any course in a Moodle 3.1 -site where local_obf is installed, it crashes midprocess and with following error in the error-log:

PHP Fatal error:  Using $this when not in object context in {moodledir}/local/obf/classes/observer.php on line 147, referer: {moodlesite}/course/delete.php?id=71

**Comment by jounisuo** [comment]
Thanks for the report,
Commit https://github.com/discendum/obf-moodle/commit/e85df5976e1b42bfeae633630aa0610e62e1ae11 should fix the issue.
