### ISSUE TITLE
error - not compatible with php 7.2

### ISSUE THREAD

**Issue by nuria2c** [discendum/obf-moodle#14]
The plugin is not working correctly with a moodle 3.6 and a php server 7.2.
That give us problems with the sheduled tasks and can't execute the cron. This is the error message:

Fatal error: Cannot use object as object because 'object' is a special class name in /var/www/html/local/obf/classes/task/certificate_expiration_reminder.php on line 29

could you update the plugin and make it compatible with moodle 3.6 and php 7.2?

**Comment by JamesNGarrett** [comment]
For those reading this prior to the next patch it's an easy fix. Moodle used to have a class called object for generic objects but this was removed from core for php7 compatibility. Generally it can be replaced with a stdClass without any problems. Hence:

File:
/local/obf/classes/task/certificate_expiration_reminder.php

change line 29 from
```
use \object;
```
to
```
//use \object;
```

change line 69 from
```
$eventdata = new object();
```
to
```
$eventdata = new stdclass();
```

**Comment by heidiwik** [comment]
Install bug fixed

**Comment by heidiwik** [comment]
Install bug should be fixed now
