### ISSUE TITLE
local_obf not compatible with Moodle 3.5

### ISSUE THREAD

**Issue by kkiiskin** [discendum/obf-moodle#23]
Hi

When in Moodle 3.5 creating a new awarding rule with 'Completing a set of activities' as a method, you get the error message 
"Global function make_categories_list() is removed. 
Please use coursecat::make_categories_list() and coursecat::get_parents()"

This commit seems to have made the plugin incompatible wih 3.5 as you should still us coursecat::make_categories_list() with that version:
https://github.com/discendum/obf-moodle/commit/ceaf2cec3ce421da11cf711cee03b21945ec0e4c#diff-1682735908389d77015fbc9da5aae328

**Comment by Urpokarhu1** [comment]
any progress @heidiwik

**Comment by heidiwik** [comment]
Hi, issue is fixed. Also tested in Moodle 3.9.
