### ISSUE TITLE
Moodle "my badges" view indicates 'badges not enabled"

### ISSUE THREAD

**Issue by meggoodine** [discendum/obf-moodle#3]
Moodle is continuing to display its onboard "my badges" view  (A) (where a user's badges are typically displayed) with the message "badges are not enabled on this site" (B) 

This is going to be confusing for users. The my badges view should connect to a page where users can view all of their badges (to their "course" OBF  badges and others in their Mozilla backpack).

Moodle's onboard badge system displays badges in the user profile (C) and as well as in the "my badges" view (D). It would be great if OBF badges worked in a similar way. 

A) ![mybadges](https://cloud.githubusercontent.com/assets/10815904/6032548/404d2a24-abbf-11e4-8d58-1803713a5a14.png)

B) ![badgenotenabled](https://cloud.githubusercontent.com/assets/10815904/6032333/c1af0f2c-abbc-11e4-8686-287bc19d770e.png)

C) ![badgeprofile](https://cloud.githubusercontent.com/assets/10815904/6032493/8a761e54-abbe-11e4-8770-1aadef437e31.png)

D) ![moodlebadges](https://cloud.githubusercontent.com/assets/10815904/6032478/6ae7f5c6-abbe-11e4-8262-c31c7ce71cf8.png)

**Comment by oinp** [comment]
We have a separate displayer plugin (block-type) under development that can be used to display earned badges (currently from Mozilla Backpack), but unfortunately it's not ready for release yet. But until then, you can hide the My badges -menuitem from the menu via Site administration > Appearance > Themes > Theme settings > User menu items to prevent confusion.

**Comment by jounisuo** [comment]
A displayer plugin has been released, which supportst Mozilla Backpack, Open Badge Passport, OBF and Moodle badges. Closing this issue.
