### ISSUE TITLE
Suspicious dependency on totara code and database tables

### ISSUE THREAD

**Issue by mudrd8mz** [discendum/obf-moodle#6]
In class/criterion/totaraprogram.php there is `$sql = "SELECT * FROM {prog} WHERE id " . $insql;` or `require_once($CFG->dirroot . '/totara/program/program.class.php');`

Do I get it right that the totaraprogram class is used only when the `$CFG->totara_build` exists?

**Comment by jounisuo** [comment]
Yes, you are correct. totaraprogram class is only used when $CFG->totara_build exists, and it handles totara programs and certificates.

**Comment by mudrd8mz** [comment]
Thanks.
