### ISSUE TITLE
Navigation node add_before: Reference node not found backup, options: grades

### ISSUE THREAD

**Issue by mudrd8mz** [discendum/obf-moodle#8]
Just ran into this, logged in as a student with developer debugging on:

    Navigation node add_before: Reference node not found backup, options: grades
    line 793 of /lib/navigationlib.php: call to debugging()
    line 342 of /lib/navigationlib.php: call to navigation_node_collection->add()
    line 213 of /local/obf/lib.php: call to navigation_node->add_node()
    line 161 of /local/obf/lib.php: call to local_obf_add_course_admin_container()
    line 4748 of /lib/navigationlib.php: call to local_obf_extend_settings_navigation()
    line 3529 of /lib/navigationlib.php: call to settings_navigation->load_local_plugin_settings()
    line 719 of /lib/pagelib.php: call to settings_navigation->initialise()
    line 768 of /lib/pagelib.php: call to moodle_page->magic_get_settingsnav()
    line 135 of /blocks/settings/block_settings.php: call to moodle_page->__get()
    line 288 of /blocks/moodleblock.class.php: call to block_settings->get_content()
    line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
    line 971 of /lib/blocklib.php: call to block_base->get_content_for_output()
    line 1023 of /lib/blocklib.php: call to block_manager->create_block_contents()
    line 473 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
    line 52 of /theme/clean/layout/columns3.php: call to core_renderer->standard_head_html()
    line 1015 of /lib/outputrenderers.php: call to include()
    line 945 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 244 of /course/view.php: call to core_renderer->header()

**Comment by jounisuo** [comment]
Thanks for reporting.

With the last commit, students will no longer get the admin container at all, and node should be created without warnings even when backup setting is not present.
