### ISSUE TITLE
Deprecated Events API

### ISSUE THREAD

**Issue by kkiiskin** [discendum/obf-moodle#9]
When installing to Moodle 3.1.2, the following warning is shown

local_obf
Events API using $handlers array has been deprecated in favour of Events 2 API, please use it instead.

    line 4050 of /lib/deprecatedlib.php: call to debugging()
    line 533 of /lib/upgradelib.php: call to events_update_definition()
    line 1742 of /lib/upgradelib.php: call to upgrade_plugins()
    line 683 of /admin/index.php: call to upgrade_noncore()

Same kind of warning is visible in the admin-page after installation.

**Comment by jounisuo** [comment]
We've now pushed new Events 2 API changes to github.

**Comment by jounisuo** [comment]
This should be fixed in the 0.2.9 version released yesterday at https://moodle.org/plugins/local_obf
